AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, SupportedStyles.
Style/SignalException:
  EnforcedStyle: only_raise

# Configuration parameters: Max
Metrics/CyclomaticComplexity:
  Enabled: false

# Configuration parameters: Max
Metrics/PerceivedComplexity:
  Enabled: false

# Configuration parameters: CountKeywordArgs, Max.
Metrics/ParameterLists:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

# Configuration parameters: AllowURI, URISchemes, Max
Metrics/LineLength:
  Enabled: false

# Configuration parameters: Max, CountComments.
Metrics/MethodLength:
  Enabled: false

# Configuration parameters: Max
Metrics/AbcSize:
  Enabled: false

# Configuration parameters: CountComments, Max.
Metrics/ClassLength:
  Enabled: false

# Configuration parameters: Max
Metrics/BlockNesting:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
