---
version: "3"
services:
  main:
    build: .
    volumes:
      - .:/app/compta
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Applications/Compta:/dropbox
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Applications/Gnucash:/gnucash
      - ~/.pryrc:/root/.pryrc
      - ~/.pry_history:/root/.pry_history
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    links:
      - db
      - redis

  postgres: &POSTGRES
    image: postgres:9.5
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      PGPASSWORD: mysecretpassword
      PGDATA: /var/lib/postgresql/data/pgdata

  redis:
    image: redis:3.2-alpine

  db:
    <<: *POSTGRES
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "65432:5432"

  psql:
    <<: *POSTGRES
    entrypoint: psql --host=db --port=5432 --username=postgres --dbname=compta_development
    volumes:
      - .:/app/compta
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Applications/Compta:/dropbox
    links:
      - db

  pg_dump:
    <<: *POSTGRES
    entrypoint: pg_dump --host=db --port=5432 --username=postgres --dbname=compta_development
    volumes:
      - .:/app/compta
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Applications/Compta:/dropbox
    links:
      - db

  pg_restore:
    <<: *POSTGRES
    entrypoint: pg_restore --host=db --port=5432 --username=postgres --dbname=compta_development
    volumes:
      - .:/app/compta
      - ~/Library/Mobile Documents/com~apple~CloudDocs/Applications/Compta:/dropbox
    links:
      - db
